In [16]:
grid = [[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 2, 0, 0, 0, 0, 0, 0]]

In [17]:
import numpy as np

def possible(y,x,n):
    global grid
    for i in range(0, 9):
        if grid[y][i] == n:
            return False

    for i in range(0, 9):
        if grid[i][x] == n:
            return False
    x0 = (x//3) * 3
    y0 = (y//3) * 3

    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == n:
                return False

    return True


In [18]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))


In [19]:
solve()

[[2 1 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [3 2 1 5 4 7 6 9 8]
 [5 4 7 6 9 8 2 3 1]
 [6 9 8 2 3 1 5 4 7]
 [8 6 4 3 1 2 9 7 5]
 [9 7 5 8 6 4 3 1 2]
 [1 3 2 9 7 5 8 6 4]]
[[2 1 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [3 2 1 5 4 7 6 9 8]
 [5 4 7 6 9 8 2 3 1]
 [6 9 8 2 3 1 5 4 7]
 [8 6 4 3 1 5 9 7 2]
 [9 7 5 8 6 2 3 1 4]
 [1 3 2 9 7 4 8 6 5]]
[[2 1 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [3 2 1 5 4 7 6 9 8]
 [5 4 7 6 9 8 2 3 1]
 [6 9 8 2 3 1 5 4 7]
 [8 6 4 3 7 2 9 1 5]
 [9 7 5 8 1 4 3 6 2]
 [1 3 2 9 6 5 8 7 4]]


KeyboardInterrupt: Interrupted by user

In [1]:
import numpy as np

x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
print(y.shape)
print(y)


x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
print(y.shape)


f= 'firelol'

print(f[:-1])

(4,)
[1.16063153 3.15819927 2.19381542 2.09540159]
(1, 2)
firelo


In [4]:
import tensorflow as tf 

gpu_available = tf.test.is_gpu_available()
is_cuda_gpu_available = tf.test.is_gpu_available(cuda_only=True)
print(f'{gpu_available = }')
print(f'{is_cuda_gpu_available = }')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True